/**
 * @file IFileService.ts
 *
 * Shared file inventory contract published by the Pages module under the
 * service registry name `'files'`. Every file the platform stores — admin
 * page attachments, plugin-generated images, future imports — flows through
 * this interface so there is a single source of truth for file bytes,
 * metadata, and discovery.
 *
 * Files are referenced by globally unique UUIDs (not paths). Internal storage
 * paths are an implementation detail that consumers never see; they ask the
 * service for a record by id and receive bytes, MIME type, and a public URL.
 *
 * Sources (`IFileSource`) namespace each file so consumers can filter listings
 * to their own outputs and operators can reason about disk usage by source.
 * The namespace is not a security boundary — `read()` is open across sources
 * by design, because cross-source consumption (e.g. `memo-tracker` rendering
 * an image generated by `image-gen`) is the whole point. `list()` is honor-
 * system: callers should pass their own source filter unless they have a
 * specific reason to enumerate platform-wide files.
 */

/**
 * Origin classification for a stored file. Used both as a list filter and as
 * the on-disk path namespace prefix (`/uploads/<kind>/<id>/...`), giving
 * operators a clear filesystem story for "which files came from which
 * subsystem".
 *
 * - `'core'` — Files written by the platform itself (rare; reserved).
 * - `'module'` — Files owned by a built-in module (e.g. Pages admin uploads
 *               use `{ kind: 'module', id: 'pages' }`).
 * - `'plugin'` — Files produced by an installed plugin (e.g. image-gen uses
 *               `{ kind: 'plugin', id: 'image-gen' }`).
 */
export interface IFileSource {
    kind: 'core' | 'module' | 'plugin';
    /**
     * Stable identifier within the kind. For modules this is the module id
     * (`'pages'`, `'menu'`); for plugins the manifest id (`'image-gen'`,
     * `'memo-tracker'`); for core a short tag identifying the subsystem.
     */
    id: string;
}

/**
 * Public file record returned by the service. The `id` is the durable handle
 * consumers retain; `url` is the browser-safe address resolved against the
 * configured storage backend at the moment the record was produced. Internal
 * storage handles (provider keys, on-disk paths) are deliberately not surfaced
 * — they are an implementation detail of the active backend and would tempt
 * consumers to bypass `IFileService`.
 */
export interface IFileRecord {
    /** Globally unique UUID. Stable for the lifetime of the file. */
    id: string;

    /** Origin namespace. */
    source: IFileSource;

    /** Original filename supplied at upload time, retained for display. */
    originalName: string;

    /** Sanitized name actually written to storage. */
    storedName: string;

    /** MIME type recorded at upload (e.g. `image/png`). */
    mimeType: string;

    /** Size of the stored bytes. */
    sizeBytes: number;

    /**
     * Public URL-relative address suitable for browser display. Resolved at
     * record-construction time so callers can render listings without an
     * extra `getUrl(id)` round-trip per row. Backends that surface CDN URLs
     * (future S3/R2) populate this field with the public form; local FS
     * echoes the `/uploads/...` path Express serves.
     */
    url: string;

    /** Optional uploader identity (user id, plugin context, etc.). */
    uploadedBy: string | null;

    /** Wall-clock timestamp at upload. */
    uploadedAt: Date;
}

/**
 * Caller-supplied options on `upload()`. The `source` field is required so
 * every file is namespaced; there is no implicit fallback. `uploadedBy` is
 * optional and meant for systems that have a user identity to attach.
 */
export interface IFileUploadOptions {
    source: IFileSource;
    uploadedBy?: string | null;
}

/**
 * Filter shape for `list()`. All fields are optional and combine as AND
 * predicates. Pass `source` to scope results to your own files (the expected
 * default for plugins and modules). Pass `mimeType` as a prefix (`'image/'`)
 * to constrain by format family.
 */
export interface IFileListFilter {
    source?: IFileSource;
    mimeType?: string;
    limit?: number;
    skip?: number;
}

/**
 * Validation failure raised by `IFileService.upload()` when caller-supplied
 * bytes do not meet platform policy (extension whitelist, future content-type
 * checks, etc.). Consumers map this to HTTP 400 (Bad Request) or its protocol
 * equivalent. Extending plain `Error` keeps the contract dependency-free for
 * downstream plugins.
 */
export class FileValidationError extends Error {
    constructor(message: string) {
        super(message);
        this.name = 'FileValidationError';
    }
}

/**
 * Specialization of `FileValidationError` for size-policy violations.
 * Consumers map this to HTTP 413 (Payload Too Large). Kept distinct from the
 * base class so a generic `instanceof FileValidationError` catch still covers
 * size errors when finer routing isn't needed.
 */
export class FileSizeExceededError extends FileValidationError {
    constructor(message: string) {
        super(message);
        this.name = 'FileSizeExceededError';
    }
}

/**
 * Service contract for the unified file inventory. Implemented inside the
 * Pages module and published on the service registry as `'files'` for module
 * and plugin consumers.
 */
export interface IFileService {
    /**
     * Persist new bytes and return the resulting record. The service generates
     * the UUID, sanitizes the filename, validates against module-level
     * settings (max size, allowed extensions), writes to storage under the
     * source-namespaced path, and inserts the inventory row.
     *
     * @throws Error when validation fails (size, extension) or storage write fails.
     */
    upload(
        bytes: Buffer,
        originalName: string,
        mimeType: string,
        options: IFileUploadOptions
    ): Promise<IFileRecord>;

    /**
     * Read bytes for a previously uploaded file. Cross-source by design —
     * holding the id is sufficient. Returns null if the id does not resolve.
     */
    read(id: string): Promise<{ bytes: Buffer; mimeType: string } | null>;

    /**
     * Resolve a public URL for browser display from the id alone. Convenience
     * for callers that hold only an id; consumers that already have an
     * `IFileRecord` from `list()`/`getRecord()` should read `record.url`
     * directly to avoid an extra inventory lookup. Returns null when the id
     * does not resolve.
     */
    getUrl(id: string): Promise<string | null>;

    /**
     * Fetch a single record without reading bytes. Useful for displaying
     * metadata (mime, size, uploader) without loading the file.
     */
    getRecord(id: string): Promise<IFileRecord | null>;

    /**
     * Enumerate records matching the filter, sorted by `uploadedAt` desc.
     * Honor system: callers should pass their own `source` unless they have
     * a defensible reason (admin tooling, cross-source dashboards).
     */
    list(filter?: IFileListFilter): Promise<IFileRecord[]>;

    /**
     * Count records matching the filter (same semantics as `list()` minus the
     * pagination fields).
     */
    count(filter?: Omit<IFileListFilter, 'limit' | 'skip'>): Promise<number>;

    /**
     * Remove the inventory row and the underlying bytes. Returns true when a
     * record was deleted, false when the id did not exist. Storage-layer
     * "file already missing" is treated as success (returns true) so callers
     * can clean up orphaned references without exception handling.
     */
    delete(id: string): Promise<boolean>;
}
