#!/bin/bash

###############################################################################
# Cloudflare DNS A Record Creation Script
#
# Purpose:
#   Creates an A record in Cloudflare DNS for PR environment subdomains.
#   Used by GitHub Actions to dynamically provision DNS for each PR.
#
# Why this matters:
#   - Eliminates need for reserved static IPs
#   - Enables wildcard SSL certificate usage across all PRs
#   - Allows unlimited PR environments without rate limit concerns
#
# Usage:
#   ./cloudflare-dns-add.sh <subdomain> <ip_address>
#
# Example:
#   ./cloudflare-dns-add.sh pr-42 192.0.2.1
#   # Creates: pr-42.dev-pr.tronrelic.com -> 192.0.2.1
#
# Required Environment Variables:
#   CLOUDFLARE_API_TOKEN - API token with DNS edit permissions
#   CLOUDFLARE_ZONE_ID - Zone ID for tronrelic.com domain
#
# Exit Codes:
#   0 - Success (record created or already exists)
#   1 - Invalid arguments
#   2 - Missing environment variables
#   3 - Cloudflare API error
###############################################################################

set -euo pipefail

# Configuration
BASE_DOMAIN="dev-pr.tronrelic.com"
CLOUDFLARE_API_URL="https://api.cloudflare.com/client/v4"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Functions for colored output
error() {
    echo -e "${RED}❌ Error: $1${NC}" >&2
}

success() {
    echo -e "${GREEN}✅ $1${NC}"
}

info() {
    echo -e "${YELLOW}ℹ️  $1${NC}"
}

# Validate arguments
if [ $# -ne 2 ]; then
    error "Invalid number of arguments"
    echo "Usage: $0 <subdomain> <ip_address>" >&2
    echo "Example: $0 pr-42 192.0.2.1" >&2
    exit 1
fi

SUBDOMAIN="$1"
IP_ADDRESS="$2"
FULL_DOMAIN="${SUBDOMAIN}.${BASE_DOMAIN}"

# Validate environment variables
if [ -z "${CLOUDFLARE_API_TOKEN:-}" ]; then
    error "CLOUDFLARE_API_TOKEN environment variable is not set"
    exit 2
fi

if [ -z "${CLOUDFLARE_ZONE_ID:-}" ]; then
    error "CLOUDFLARE_ZONE_ID environment variable is not set"
    exit 2
fi

# Validate IP address format (basic check)
if ! echo "$IP_ADDRESS" | grep -qE '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'; then
    error "Invalid IP address format: $IP_ADDRESS"
    exit 1
fi

info "Creating DNS A record: ${FULL_DOMAIN} -> ${IP_ADDRESS}"

# Check if record already exists
info "Checking for existing DNS record..."
EXISTING_RECORD=$(curl -s -X GET \
    "${CLOUDFLARE_API_URL}/zones/${CLOUDFLARE_ZONE_ID}/dns_records?type=A&name=${FULL_DOMAIN}" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json")

# Check if API request was successful
if ! echo "$EXISTING_RECORD" | jq -e '.success' > /dev/null 2>&1; then
    error "Failed to query Cloudflare API"
    echo "$EXISTING_RECORD" | jq '.' >&2
    exit 3
fi

RECORD_COUNT=$(echo "$EXISTING_RECORD" | jq -r '.result | length')

if [ "$RECORD_COUNT" -gt 0 ]; then
    EXISTING_IP=$(echo "$EXISTING_RECORD" | jq -r '.result[0].content')
    RECORD_ID=$(echo "$EXISTING_RECORD" | jq -r '.result[0].id')
    
    if [ "$EXISTING_IP" = "$IP_ADDRESS" ]; then
        success "DNS record already exists with correct IP: ${FULL_DOMAIN} -> ${IP_ADDRESS}"
        exit 0
    else
        info "DNS record exists with different IP (${EXISTING_IP}), updating to ${IP_ADDRESS}..."
        
        # Update existing record
        UPDATE_RESPONSE=$(curl -s -X PUT \
            "${CLOUDFLARE_API_URL}/zones/${CLOUDFLARE_ZONE_ID}/dns_records/${RECORD_ID}" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data "{
                \"type\": \"A\",
                \"name\": \"${FULL_DOMAIN}\",
                \"content\": \"${IP_ADDRESS}\",
                \"ttl\": 120,
                \"proxied\": false
            }")
        
        if echo "$UPDATE_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
            success "DNS record updated successfully: ${FULL_DOMAIN} -> ${IP_ADDRESS}"
            exit 0
        else
            error "Failed to update DNS record"
            echo "$UPDATE_RESPONSE" | jq '.' >&2
            exit 3
        fi
    fi
fi

# Create new DNS record
info "Creating new DNS A record..."
CREATE_RESPONSE=$(curl -s -X POST \
    "${CLOUDFLARE_API_URL}/zones/${CLOUDFLARE_ZONE_ID}/dns_records" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    --data "{
        \"type\": \"A\",
        \"name\": \"${FULL_DOMAIN}\",
        \"content\": \"${IP_ADDRESS}\",
        \"ttl\": 120,
        \"proxied\": false,
        \"comment\": \"Auto-generated by GitHub Actions for PR environment\"
    }")

# Check if creation was successful
if echo "$CREATE_RESPONSE" | jq -e '.success' > /dev/null 2>&1; then
    success "DNS record created successfully: ${FULL_DOMAIN} -> ${IP_ADDRESS}"
    info "DNS propagation may take a few moments..."
    exit 0
else
    error "Failed to create DNS record"
    echo "$CREATE_RESPONSE" | jq '.' >&2
    exit 3
fi
