/**
 * @file IFileService.ts
 *
 * Shared file inventory contract published by the Files module under the
 * service registry name `'files'`. Every file the platform stores — admin
 * page attachments, plugin-generated images, future imports — flows through
 * this interface so there is a single source of truth for file bytes,
 * metadata, and discovery.
 *
 * Files are referenced by globally unique UUIDs (not paths). Internal storage
 * paths are an implementation detail that consumers never see; they ask the
 * service for a record by id and receive bytes, MIME type, and a public URL.
 *
 * Sources (`IFileSource`) namespace each file so consumers can filter listings
 * to their own outputs and operators can reason about disk usage by source.
 * The namespace is not a security boundary — `read()` is open across sources
 * by design, because cross-source consumption (e.g. `memo-tracker` rendering
 * an image generated by `image-gen`) is the whole point. `list()` is honor-
 * system: callers should pass their own source filter unless they have a
 * specific reason to enumerate platform-wide files.
 */

/**
 * Origin classifications for stored files. Single source of truth — the
 * `IFileSource['kind']` type union is derived from this constant, and runtime
 * validators (e.g. the admin file-browser query parser) iterate it directly.
 */
export const FILE_SOURCE_KINDS = ['core', 'module', 'plugin'] as const;

/**
 * Origin classification for a stored file.
 */
export interface IFileSource {
    kind: (typeof FILE_SOURCE_KINDS)[number];
    /**
     * Stable identifier within the kind. For modules this is the module id
     * (`'pages'`, `'menu'`); for plugins the manifest id (`'image-gen'`,
     * `'memo-tracker'`); for core a short tag identifying the subsystem.
     */
    id: string;
}

/**
 * Public file record returned by the service. The `id` is the durable handle
 * consumers retain; `url` is the browser-safe address resolved against the
 * configured storage backend at the moment the record was produced.
 */
export interface IFileRecord {
    /** Globally unique UUID. Stable for the lifetime of the file. */
    id: string;

    /** Origin namespace. */
    source: IFileSource;

    /** Original filename supplied at upload time, retained for display. */
    originalName: string;

    /** Sanitized name actually written to storage. */
    storedName: string;

    /** MIME type recorded at upload (e.g. `image/png`). */
    mimeType: string;

    /** Size of the stored bytes. */
    sizeBytes: number;

    /** Absolute public URL (scheme + host + path) suitable for browser display
     *  and for handing to external consumers such as Telegram, X, or email. */
    url: string;

    /** Optional uploader identity (user id, plugin context, etc.). */
    uploadedBy: string | null;

    /** Wall-clock timestamp at upload. */
    uploadedAt: Date;
}

/**
 * Caller-supplied options on `upload()`. The `source` field is required so
 * every file is namespaced; there is no implicit fallback.
 */
export interface IFileUploadOptions {
    source: IFileSource;
    uploadedBy?: string | null;
}

/**
 * Filter shape for `list()`. All fields are optional and combine as AND
 * predicates.
 */
export interface IFileListFilter {
    source?: IFileSource;
    mimeType?: string;
    limit?: number;
    skip?: number;
}

/**
 * Validation failure raised by `IFileService.upload()` when caller-supplied
 * bytes do not meet platform policy. Consumers map this to HTTP 400.
 */
export class FileValidationError extends Error {
    constructor(message: string) {
        super(message);
        this.name = 'FileValidationError';
    }
}

/**
 * Specialization of `FileValidationError` for size-policy violations.
 * Consumers map this to HTTP 413.
 */
export class FileSizeExceededError extends FileValidationError {
    constructor(message: string) {
        super(message);
        this.name = 'FileSizeExceededError';
    }
}

/**
 * Service contract for the unified file inventory. Implemented inside the
 * Files module and published on the service registry as `'files'` for module
 * and plugin consumers.
 */
export interface IFileService {
    /**
     * Persist new bytes and return the resulting record. The service generates
     * the UUID, sanitizes the filename, validates against module-level
     * settings (max size, allowed extensions), writes to storage under the
     * source-namespaced path, and inserts the inventory row.
     */
    upload(
        bytes: Buffer,
        originalName: string,
        mimeType: string,
        options: IFileUploadOptions
    ): Promise<IFileRecord>;

    /**
     * Read bytes for a previously uploaded file. Cross-source by design.
     * Returns null if the id does not resolve.
     */
    read(id: string): Promise<{ bytes: Buffer; mimeType: string } | null>;

    /**
     * Resolve an absolute public URL (scheme + host + path) from the id alone.
     * Suitable for browser display and for handing to external consumers such
     * as Telegram, X, or email. Returns null when the id does not resolve.
     */
    getUrl(id: string): Promise<string | null>;

    /**
     * Fetch a single record without reading bytes.
     */
    getRecord(id: string): Promise<IFileRecord | null>;

    /**
     * Enumerate records matching the filter, sorted by `uploadedAt` desc.
     */
    list(filter?: IFileListFilter): Promise<IFileRecord[]>;

    /**
     * Count records matching the filter.
     */
    count(filter?: Omit<IFileListFilter, 'limit' | 'skip'>): Promise<number>;

    /**
     * Enumerate the distinct `{kind, id}` pairs currently present in the
     * inventory. Sorted by `(kind, id)` ascending.
     */
    distinctSources(): Promise<IFileSource[]>;

    /**
     * Remove the inventory row and the underlying bytes. Returns true when a
     * record was deleted, false when the id did not exist.
     */
    delete(id: string): Promise<boolean>;
}
